name: Step - Deploy

env:
  AZURE_WEBAPP_NAME: app-dometrain-github-actions-axel
  ARTIFACT_ROUTE: artifacts
  ARTIFACT_NAME: domatrain-artifact

on: 
  workflow_call:
    inputs:
      env:
        required: true
        type: string
    secrets:
      AZURE_CLIENT_ID:
        required: true
      AZURE_TENANT_ID:
        required: true
      AZURE_SUBSCRIPTION_ID:
        required: true

jobs:    
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: ${{inputs.env}}

    steps:
      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{env.ARTIFACT_NAME}}
          path: ${{env.ARTIFACT_ROUTE}}/

      - name: 'Deploy'
        uses: azure/webapps-deploy@v2
        with: 
          app-name: ${{env.AZURE_WEBAPP_NAME}}-${{inputs.env}}
          package: ${{env.ARTIFACT_ROUTE}}/
